source "https://rubygems.org"

gem "rails", "~> 7.2.3", ">= 7.2.3.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "redis", ">= 4.0.1"
gem "sidekiq", "~> 7.0"
gem "sidekiq-scheduler", "~> 5.0"
gem "connection_pool", "~> 2.5"
gem "rack-cors"
gem "rack-attack"
gem "jwt"
gem "bcrypt", "~> 3.1"
gem "kaminari"
gem "stripe", "~> 12.0"
gem "faraday", "~> 2.12"
gem "faraday-retry", "~> 2.2"
gem "aws-sdk-s3", require: false
gem "image_processing", "~> 1.2"
gem "dotenv-rails"
gem "bootsnap", require: false
gem "sentry-ruby"
gem "sentry-rails"
gem "sentry-sidekiq"
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Geração de PDF (relatórios)
gem "prawn"
gem "prawn-table"
# Prawn depende de matrix, que deixou de ser default gem no Ruby 3.4+
gem "matrix"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :test do
  gem "shoulda-matchers"
  gem "database_cleaner-active_record"
  gem "webmock"
  gem "pdf-reader"
end
