require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Desabilita HostAuthorization em development — permite requisições via nginx,
  # Vite proxy (Host: backend:3000) e IPs de rede local.
  config.hosts.clear

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.cache_store = :memory_store
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local
  config.active_storage.service_urls_expire_in = 1.year
  config.active_storage.variant_processor = :vips

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Disable caching for Action Mailer templates even if Action Controller
  # caching is enabled.
  config.action_mailer.perform_caching = false

  # Action Mailer — same credentials-backed SMTP config as production, so
  # dev sends through the real Hostinger SMTP when needed (smoke tests,
  # template previews). Errors stay silent in dev via raise_delivery_errors.
  config.action_mailer.delivery_method    = :smtp
  config.action_mailer.perform_deliveries = true
  config.action_mailer.smtp_settings = {
    address:              Rails.application.credentials.dig(:smtp, :address),
    port:                 Rails.application.credentials.dig(:smtp, :port),
    domain:               Rails.application.credentials.dig(:smtp, :domain),
    user_name:            Rails.application.credentials.dig(:smtp, :user_name),
    password:             Rails.application.credentials.dig(:smtp, :password),
    authentication:       Rails.application.credentials.dig(:smtp, :authentication)&.to_sym || :login,
    tls:                  Rails.application.credentials.dig(:smtp, :tls),
    enable_starttls_auto: false
  }

  # HOST_URL controls Active Storage redirect URLs and action mailer links.
  # docker-compose injects HOST_URL=http://localhost; start.sh overrides with
  # the detected LAN IP so mobile/tablet clients can reach image URLs directly.
  # Defaults to http://localhost so Active Storage never falls back to the
  # Docker-internal service name "backend" when HOST_URL is absent.
  _host_url  = ENV.fetch("HOST_URL", "http://localhost")
  _parts     = _host_url.sub(%r{\Ahttps?://}, "").split(":")
  _url_opts  = {
    host:     _parts[0],
    port:     _parts[1]&.to_i.presence,
    protocol: _host_url.start_with?("https") ? "https" : "http"
  }

  config.action_controller.default_url_options   = _url_opts
  config.action_mailer.default_url_options        = { host: _parts[0], port: _parts[1]&.to_i.presence }
  Rails.application.routes.default_url_options    = _url_opts

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
